leftnav:
- identifier: 39cb986d-2fc1-dd6c-647b-41889e653883
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e56a99a8-4a85-ac25-70d1-6fc9ae594c05
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 7260bf36-bd91-0186-b5f6-ebacdf99bc79
  name: Recitations
  url: /pages/recitations
  weight: 30
- identifier: 471fe7eb-397f-55dd-b657-a24eed413248
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 92131f5e-bdba-6bbf-f9ed-96a5edede73a
  name: Exams
  url: /pages/exams
  weight: 50
